language: java

notifications:
  email: false

services:
  - docker

before_script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker-compose build eureka-server
  - docker images
