language: java

notifications:
  email: false

jdk:
  - openjdk11

services:
  - docker

before_script:
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  docker build -t eureka-server ./eureka-server;
  docker push eureka-server:latest
