language: java

notifications:
  email: false

jdk:
  - openjdk11

services:
  - docker

before_script:
  docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
  ./eureka-server/gradlew build --stacktrace
  pwd
  ls
  docker-compose build eureka-server
  docker push ${DOCKER_USERNAME}/*_eureka-server:latest
