language: java

notifications:
  email: false

services:
  - docker

before_script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build -t $DOCKER_USERNAME/eureka-server ./eureka-server
  - docker exec -it $DOCKER_USERNAME/eureka-server /bin/bash
  - pwd && ls
#  - docker images
#  - docker push $DOCKER_USERNAME/eureka-server
